SELECT * FROM information_schema.TABLES

select * from Factures
select * from Contractors
select * from Users
select * from Addresses
select * from Clubs
select * from Contacts
UPDATE Users set MoneyBoxId='6' where FirstName='Kacper';
SET IDENTITY_INSERT Contractors ON
INSERT INTO Contractors (Id, Pesel, NIP, REGON, Name, MainAddress,LastEditTime)
values (1, 1, 1, 1, 'Bez Wyboru', 29, '1990-01-01 00:00:00');
SET IDENTITY_INSERT Contractors OFF

ALTER TABLE Factures
DROP CONSTRAINT [FK_dbo.Factures_dbo.Users_UserId]

DELETE FROM Addresses WHERE Id=50 OR Id=51 OR Id=52 OR Id=53 OR Id=54 OR Id=57

INSERT INTO MoneyBox (Value, NumberOfUsers) values (25.43, 4);

delete from factures
SELECT sobjects.name
FROM sysobjects sobjects
WHERE sobjects.xtype = 'U'


DECLARE @SQL VARCHAR(MAX)=''
SELECT @SQL = @SQL + 'ALTER TABLE ' + QUOTENAME(FK.TABLE_SCHEMA) + '.' + QUOTENAME(FK.TABLE_NAME) + ' DROP CONSTRAINT [' + RTRIM(C.CONSTRAINT_NAME) +'];' + CHAR(13)
--SELECT K_Table = FK.TABLE_NAME, FK_Column = CU.COLUMN_NAME, PK_Table = PK.TABLE_NAME, PK_Column = PT.COLUMN_NAME, Constraint_Name = C.CONSTRAINT_NAME
  FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
 INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK
    ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
 INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK
    ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
 INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
    ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
 INNER JOIN (
            SELECT i1.TABLE_NAME, i2.COLUMN_NAME
              FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
             INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2
                ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
            WHERE i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
           ) PT
    ON PT.TABLE_NAME = PK.TABLE_NAME

EXEC (@SQL)

PRINT @SQL



DECLARE @sql NVARCHAR(max)=''

SELECT @sql += ' Drop table '+TABLE_SCHEMA+'.'+ TABLE_NAME
FROM   INFORMATION_SCHEMA.TABLES
WHERE  TABLE_TYPE = 'BASE TABLE'

Exec Sp_executesql @sql