namespace ConsoleApplication5.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class TableNamebigUpdate : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.AddressSets", newName: "Addresses");
            RenameTable(name: "dbo.BankAccountSets", newName: "BankAccounts");
            RenameTable(name: "dbo.UserSets", newName: "Users");
            RenameTable(name: "dbo.ClubInfoSets", newName: "Clubs");
            RenameTable(name: "dbo.ContactSets", newName: "Contacts");
            RenameTable(name: "dbo.ContractorSets", newName: "Contractors");
            RenameTable(name: "dbo.FactureSets", newName: "Factures");
            RenameTable(name: "dbo.ListOfItemsSets", newName: "ListOfItems");
            RenameTable(name: "dbo.DeliverySets", newName: "Deliveries");
            RenameTable(name: "dbo.BoughtPackagesSets", newName: "BoughtPackages");
            RenameTable(name: "dbo.PackagesSets", newName: "Packages");
            RenameTable(name: "dbo.ExerciseSets", newName: "Exercises");
            RenameTable(name: "dbo.RoomsSets", newName: "Rooms");
            RenameTable(name: "dbo.ExReportsSets", newName: "ExerciseReports");
            RenameTable(name: "dbo.DiscountSets", newName: "Discounts");
            RenameTable(name: "dbo.MoneyboxSet", newName: "Moneybox");
            RenameTable(name: "dbo.PayoffSet", newName: "Payoff");
            RenameTable(name: "dbo.MailerSmserSets", newName: "MailerSmsers");
            RenameTable(name: "dbo.TemplateSets", newName: "Templates");
            RenameTable(name: "dbo.WarehouseSets", newName: "Warehouses");
            RenameTable(name: "dbo.MainWarehouseSets", newName: "MainWarehouses");
            RenameTable(name: "dbo.CountMachinesSets", newName: "CountMachines");
            RenameTable(name: "dbo.ContractSets", newName: "Contracts");
            RenameTable(name: "dbo.HelpDeskPartialHistorySets", newName: "HelpDeskPartialHistories");
            RenameTable(name: "dbo.HelpdeskSets", newName: "Helpdesks");
            RenameTable(name: "dbo.PermissionsSets", newName: "Permissions");
            RenameTable(name: "dbo.RoleSets", newName: "Roles");
            RenameColumn(table: "dbo.RoomsExTypes", name: "RoomsSets_Id", newName: "Rooms_Id");
            RenameColumn(table: "dbo.AccountUsers", name: "BankAccountSets_Id", newName: "BankAccount_Id");
            RenameColumn(table: "dbo.AccountUsers", name: "UserSets_Id", newName: "User_Id");
            RenameColumn(table: "dbo.Factures", name: "CrUserId", newName: "CreatorId");
            RenameColumn(table: "dbo.Factures", name: "UpUserId", newName: "UpdateUserId");
            RenameColumn(table: "dbo.MailSmsRecipients", name: "MailerSmserSets_Id", newName: "MailerSmser_Id");
            RenameColumn(table: "dbo.MailSmsRecipients", name: "UserSets_Id", newName: "User_Id");
            RenameColumn(table: "dbo.UsersPermissions", name: "UserSets_Id", newName: "User_Id");
            RenameColumn(table: "dbo.UsersPermissions", name: "PermissionsSets_Id", newName: "Permissions_Id");
            RenameColumn(table: "dbo.UsersRoles", name: "RoleSets_Id", newName: "Role_Id");
            RenameColumn(table: "dbo.UsersRoles", name: "UserSets_Id", newName: "User_Id");
            RenameColumn(table: "dbo.Deals", name: "UserSets_Id", newName: "User_Id");
            RenameColumn(table: "dbo.ItemsOnFacture", name: "FactureSets_Id", newName: "Facture_Id");
            RenameColumn(table: "dbo.ItemsOnFacture", name: "ListOfItemsSets_Id", newName: "ListOfItems_Id");
            RenameColumn(table: "dbo.DeliveryFactures", name: "DeliverySets_Id", newName: "Delivery_Id");
            RenameColumn(table: "dbo.DeliveryFactures", name: "FactureSets_Id", newName: "Facture_Id");
            RenameColumn(table: "dbo.WarehouseFactures", name: "FactureSets_Id", newName: "Facture_Id");
            RenameColumn(table: "dbo.WarehouseFactures", name: "WarehouseSets_Id", newName: "Warehouse_Id");
            RenameColumn(table: "dbo.DeliveriedItems", name: "ListOfItemsSets_Id", newName: "ListOfItems_Id");
            RenameColumn(table: "dbo.DeliveriedItems", name: "DeliverySets_Id", newName: "Delivery_Id");
            RenameColumn(table: "dbo.PackagesDiscounts", name: "DiscountSets_Id", newName: "Discount_Id");
            RenameColumn(table: "dbo.PackagesDiscounts", name: "PackagesSets_Id", newName: "Packages_Id");
            RenameColumn(table: "dbo.RolePermissions", name: "PermissionsSets_Id", newName: "Permissions_Id");
            RenameColumn(table: "dbo.RolePermissions", name: "RoleSets_Id", newName: "Role_Id");
            RenameIndex(table: "dbo.Factures", name: "IX_CrUserId", newName: "IX_CreatorId");
            RenameIndex(table: "dbo.Factures", name: "IX_UpUserId", newName: "IX_UpdateUserId");
            RenameIndex(table: "dbo.Deals", name: "IX_UserSets_Id", newName: "IX_User_Id");
            RenameIndex(table: "dbo.DeliveryFactures", name: "IX_DeliverySets_Id", newName: "IX_Delivery_Id");
            RenameIndex(table: "dbo.DeliveryFactures", name: "IX_FactureSets_Id", newName: "IX_Facture_Id");
            RenameIndex(table: "dbo.DeliveriedItems", name: "IX_ListOfItemsSets_Id", newName: "IX_ListOfItems_Id");
            RenameIndex(table: "dbo.DeliveriedItems", name: "IX_DeliverySets_Id", newName: "IX_Delivery_Id");
            RenameIndex(table: "dbo.ItemsOnFacture", name: "IX_FactureSets_Id", newName: "IX_Facture_Id");
            RenameIndex(table: "dbo.ItemsOnFacture", name: "IX_ListOfItemsSets_Id", newName: "IX_ListOfItems_Id");
            RenameIndex(table: "dbo.RoomsExTypes", name: "IX_RoomsSets_Id", newName: "IX_Rooms_Id");
            RenameIndex(table: "dbo.PackagesDiscounts", name: "IX_DiscountSets_Id", newName: "IX_Discount_Id");
            RenameIndex(table: "dbo.PackagesDiscounts", name: "IX_PackagesSets_Id", newName: "IX_Packages_Id");
            RenameIndex(table: "dbo.MailSmsRecipients", name: "IX_MailerSmserSets_Id", newName: "IX_MailerSmser_Id");
            RenameIndex(table: "dbo.MailSmsRecipients", name: "IX_UserSets_Id", newName: "IX_User_Id");
            RenameIndex(table: "dbo.WarehouseFactures", name: "IX_FactureSets_Id", newName: "IX_Facture_Id");
            RenameIndex(table: "dbo.WarehouseFactures", name: "IX_WarehouseSets_Id", newName: "IX_Warehouse_Id");
            RenameIndex(table: "dbo.UsersRoles", name: "IX_RoleSets_Id", newName: "IX_Role_Id");
            RenameIndex(table: "dbo.UsersRoles", name: "IX_UserSets_Id", newName: "IX_User_Id");
            RenameIndex(table: "dbo.RolePermissions", name: "IX_PermissionsSets_Id", newName: "IX_Permissions_Id");
            RenameIndex(table: "dbo.RolePermissions", name: "IX_RoleSets_Id", newName: "IX_Role_Id");
            RenameIndex(table: "dbo.UsersPermissions", name: "IX_UserSets_Id", newName: "IX_User_Id");
            RenameIndex(table: "dbo.UsersPermissions", name: "IX_PermissionsSets_Id", newName: "IX_Permissions_Id");
            RenameIndex(table: "dbo.AccountUsers", name: "IX_BankAccountSets_Id", newName: "IX_BankAccount_Id");
            RenameIndex(table: "dbo.AccountUsers", name: "IX_UserSets_Id", newName: "IX_User_Id");
        }
        
        public override void Down()
        {
            RenameIndex(table: "dbo.AccountUsers", name: "IX_User_Id", newName: "IX_UserSets_Id");
            RenameIndex(table: "dbo.AccountUsers", name: "IX_BankAccount_Id", newName: "IX_BankAccountSets_Id");
            RenameIndex(table: "dbo.UsersPermissions", name: "IX_Permissions_Id", newName: "IX_PermissionsSets_Id");
            RenameIndex(table: "dbo.UsersPermissions", name: "IX_User_Id", newName: "IX_UserSets_Id");
            RenameIndex(table: "dbo.RolePermissions", name: "IX_Role_Id", newName: "IX_RoleSets_Id");
            RenameIndex(table: "dbo.RolePermissions", name: "IX_Permissions_Id", newName: "IX_PermissionsSets_Id");
            RenameIndex(table: "dbo.UsersRoles", name: "IX_User_Id", newName: "IX_UserSets_Id");
            RenameIndex(table: "dbo.UsersRoles", name: "IX_Role_Id", newName: "IX_RoleSets_Id");
            RenameIndex(table: "dbo.WarehouseFactures", name: "IX_Warehouse_Id", newName: "IX_WarehouseSets_Id");
            RenameIndex(table: "dbo.WarehouseFactures", name: "IX_Facture_Id", newName: "IX_FactureSets_Id");
            RenameIndex(table: "dbo.MailSmsRecipients", name: "IX_User_Id", newName: "IX_UserSets_Id");
            RenameIndex(table: "dbo.MailSmsRecipients", name: "IX_MailerSmser_Id", newName: "IX_MailerSmserSets_Id");
            RenameIndex(table: "dbo.PackagesDiscounts", name: "IX_Packages_Id", newName: "IX_PackagesSets_Id");
            RenameIndex(table: "dbo.PackagesDiscounts", name: "IX_Discount_Id", newName: "IX_DiscountSets_Id");
            RenameIndex(table: "dbo.RoomsExTypes", name: "IX_Rooms_Id", newName: "IX_RoomsSets_Id");
            RenameIndex(table: "dbo.ItemsOnFacture", name: "IX_ListOfItems_Id", newName: "IX_ListOfItemsSets_Id");
            RenameIndex(table: "dbo.ItemsOnFacture", name: "IX_Facture_Id", newName: "IX_FactureSets_Id");
            RenameIndex(table: "dbo.DeliveriedItems", name: "IX_Delivery_Id", newName: "IX_DeliverySets_Id");
            RenameIndex(table: "dbo.DeliveriedItems", name: "IX_ListOfItems_Id", newName: "IX_ListOfItemsSets_Id");
            RenameIndex(table: "dbo.DeliveryFactures", name: "IX_Facture_Id", newName: "IX_FactureSets_Id");
            RenameIndex(table: "dbo.DeliveryFactures", name: "IX_Delivery_Id", newName: "IX_DeliverySets_Id");
            RenameIndex(table: "dbo.Deals", name: "IX_User_Id", newName: "IX_UserSets_Id");
            RenameIndex(table: "dbo.Factures", name: "IX_UpdateUserId", newName: "IX_UpUserId");
            RenameIndex(table: "dbo.Factures", name: "IX_CreatorId", newName: "IX_CrUserId");
            RenameColumn(table: "dbo.RolePermissions", name: "Role_Id", newName: "RoleSets_Id");
            RenameColumn(table: "dbo.RolePermissions", name: "Permissions_Id", newName: "PermissionsSets_Id");
            RenameColumn(table: "dbo.PackagesDiscounts", name: "Packages_Id", newName: "PackagesSets_Id");
            RenameColumn(table: "dbo.PackagesDiscounts", name: "Discount_Id", newName: "DiscountSets_Id");
            RenameColumn(table: "dbo.DeliveriedItems", name: "Delivery_Id", newName: "DeliverySets_Id");
            RenameColumn(table: "dbo.DeliveriedItems", name: "ListOfItems_Id", newName: "ListOfItemsSets_Id");
            RenameColumn(table: "dbo.WarehouseFactures", name: "Warehouse_Id", newName: "WarehouseSets_Id");
            RenameColumn(table: "dbo.WarehouseFactures", name: "Facture_Id", newName: "FactureSets_Id");
            RenameColumn(table: "dbo.DeliveryFactures", name: "Facture_Id", newName: "FactureSets_Id");
            RenameColumn(table: "dbo.DeliveryFactures", name: "Delivery_Id", newName: "DeliverySets_Id");
            RenameColumn(table: "dbo.ItemsOnFacture", name: "ListOfItems_Id", newName: "ListOfItemsSets_Id");
            RenameColumn(table: "dbo.ItemsOnFacture", name: "Facture_Id", newName: "FactureSets_Id");
            RenameColumn(table: "dbo.Deals", name: "User_Id", newName: "UserSets_Id");
            RenameColumn(table: "dbo.UsersRoles", name: "User_Id", newName: "UserSets_Id");
            RenameColumn(table: "dbo.UsersRoles", name: "Role_Id", newName: "RoleSets_Id");
            RenameColumn(table: "dbo.UsersPermissions", name: "Permissions_Id", newName: "PermissionsSets_Id");
            RenameColumn(table: "dbo.UsersPermissions", name: "User_Id", newName: "UserSets_Id");
            RenameColumn(table: "dbo.MailSmsRecipients", name: "User_Id", newName: "UserSets_Id");
            RenameColumn(table: "dbo.MailSmsRecipients", name: "MailerSmser_Id", newName: "MailerSmserSets_Id");
            RenameColumn(table: "dbo.Factures", name: "UpdateUserId", newName: "UpUserId");
            RenameColumn(table: "dbo.Factures", name: "CreatorId", newName: "CrUserId");
            RenameColumn(table: "dbo.AccountUsers", name: "User_Id", newName: "UserSets_Id");
            RenameColumn(table: "dbo.AccountUsers", name: "BankAccount_Id", newName: "BankAccountSets_Id");
            RenameColumn(table: "dbo.RoomsExTypes", name: "Rooms_Id", newName: "RoomsSets_Id");
            RenameTable(name: "dbo.Roles", newName: "RoleSets");
            RenameTable(name: "dbo.Permissions", newName: "PermissionsSets");
            RenameTable(name: "dbo.Helpdesks", newName: "HelpdeskSets");
            RenameTable(name: "dbo.HelpDeskPartialHistories", newName: "HelpDeskPartialHistorySets");
            RenameTable(name: "dbo.Contracts", newName: "ContractSets");
            RenameTable(name: "dbo.CountMachines", newName: "CountMachinesSets");
            RenameTable(name: "dbo.MainWarehouses", newName: "MainWarehouseSets");
            RenameTable(name: "dbo.Warehouses", newName: "WarehouseSets");
            RenameTable(name: "dbo.Templates", newName: "TemplateSets");
            RenameTable(name: "dbo.MailerSmsers", newName: "MailerSmserSets");
            RenameTable(name: "dbo.Payoff", newName: "PayoffSet");
            RenameTable(name: "dbo.Moneybox", newName: "MoneyboxSet");
            RenameTable(name: "dbo.Discounts", newName: "DiscountSets");
            RenameTable(name: "dbo.ExerciseReports", newName: "ExReportsSets");
            RenameTable(name: "dbo.Rooms", newName: "RoomsSets");
            RenameTable(name: "dbo.Exercises", newName: "ExerciseSets");
            RenameTable(name: "dbo.Packages", newName: "PackagesSets");
            RenameTable(name: "dbo.BoughtPackages", newName: "BoughtPackagesSets");
            RenameTable(name: "dbo.Deliveries", newName: "DeliverySets");
            RenameTable(name: "dbo.ListOfItems", newName: "ListOfItemsSets");
            RenameTable(name: "dbo.Factures", newName: "FactureSets");
            RenameTable(name: "dbo.Contractors", newName: "ContractorSets");
            RenameTable(name: "dbo.Contacts", newName: "ContactSets");
            RenameTable(name: "dbo.Clubs", newName: "ClubInfoSets");
            RenameTable(name: "dbo.Users", newName: "UserSets");
            RenameTable(name: "dbo.BankAccounts", newName: "BankAccountSets");
            RenameTable(name: "dbo.Addresses", newName: "AddressSets");
        }
    }
}
