// <auto-generated />
namespace RakietaLogikaBiznesowa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MoneyBoxValueisdecimalnow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoneyBoxValueisdecimalnow));
        
        string IMigrationMetadata.Id
        {
            get { return "201605101111467_MoneyBox.Value is decimal now"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
