//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication5
{
    using System;
    
    public enum MaleFemale : byte
    {
        Kobieta = 1,
        Mężczyzna = 0
    }
}
