//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication5
{
    using System;
    
    public enum TypeOfPackage : short
    {
        IlośćWejść = 1,
        Czasowy = 2,
        CrossFitWejścia = 3,
        CrossFitCzasowy = 4
    }
}
