//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication5
{
    using System;
    
    public enum HelpdeskStatus : short
    {
        Zgłoszone = 1,
        Przydzielone = 2,
        Rozwiązane = 3,
        PotrzebujęWsparcia = 4
    }
}
