//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RakietaLogikaBiznesowa.Models
{
    using System;
    
    public enum FactureCategory : short
    {
        ZwykłaFaktura = 1,
        FakturaPłatnikaZwolnionegoOdVat = 2,
        FakturaProForma = 3,
        FakturaZaliczkowa = 4
    }
}
