//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RakietaLogikaBiznesowa.Models
{
    using System;
    
    public enum FunctionPermission : int
    {
        DodawanieZajęć = 1,
        RezerwacjaSal = 2,
        ZapisyNaZajęcia = 3,
        DodawanieFaktur = 4,
        SprzedazTowaru = 5
    }
}
