//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RakietaLogikaBiznesowa.Models
{
    using System;
    
    public enum HelpdeskTypeOf : byte
    {
        Pytanie = 1,
        Sugesta = 2,
        Skarga = 3,
        Awaria = 4
    }
}
