//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RakietaLogikaBiznesowa.Models
{
    using System;
    
    public enum TypeOfProduct : short
    {
        MaszynaTreningowa = 1,
        Ciężarki = 2,
        Woda = 3,
        NapójEnergetyczny = 4,
        Baton = 5
    }
}
